/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/checkout`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/order-success`; params?: Router.UnknownInputParams; } | { pathname: `/track-order`; params?: Router.UnknownInputParams; } | { pathname: `/video-player`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/bookmarks` | `/bookmarks`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/cart` | `/cart`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/search` | `/search`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/artist/[artistId]`, params: Router.UnknownInputParams & { artistId: string | number; } } | { pathname: `/chat/[artistId]`, params: Router.UnknownInputParams & { artistId: string | number; } } | { pathname: `/product/[productId]`, params: Router.UnknownInputParams & { productId: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/checkout`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/order-success`; params?: Router.UnknownOutputParams; } | { pathname: `/track-order`; params?: Router.UnknownOutputParams; } | { pathname: `/video-player`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/bookmarks` | `/bookmarks`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/cart` | `/cart`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/search` | `/search`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } } | { pathname: `/artist/[artistId]`, params: Router.UnknownOutputParams & { artistId: string; } } | { pathname: `/chat/[artistId]`, params: Router.UnknownOutputParams & { artistId: string; } } | { pathname: `/product/[productId]`, params: Router.UnknownOutputParams & { productId: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/checkout${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/order-success${`?${string}` | `#${string}` | ''}` | `/track-order${`?${string}` | `#${string}` | ''}` | `/video-player${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/bookmarks${`?${string}` | `#${string}` | ''}` | `/bookmarks${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/cart${`?${string}` | `#${string}` | ''}` | `/cart${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/search${`?${string}` | `#${string}` | ''}` | `/search${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/checkout`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/order-success`; params?: Router.UnknownInputParams; } | { pathname: `/track-order`; params?: Router.UnknownInputParams; } | { pathname: `/video-player`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/bookmarks` | `/bookmarks`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/cart` | `/cart`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/search` | `/search`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | `/artist/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/chat/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/product/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/artist/[artistId]`, params: Router.UnknownInputParams & { artistId: string | number; } } | { pathname: `/chat/[artistId]`, params: Router.UnknownInputParams & { artistId: string | number; } } | { pathname: `/product/[productId]`, params: Router.UnknownInputParams & { productId: string | number; } };
    }
  }
}
